trigger:
  branches:
    include
      - main

pool:
  name: default


stages:
  - stage:  Initialization
    job: TerraformInit
    steps:
      - task: TerraformInstaller@1
          inputs:
            terraformVersion: $(terraformVersion)

        # Initialize Terraform
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'Azure subscription 1(4e0a7571-b8f5-4720-bda0-4220088a96a3)'
